[package]
name = "bytebot-agent-rs"
version = "0.1.0"
edition = "2021"
description = "ByteBot AI agent service written in Rust"
authors = ["ByteBot Team"]

[lib]
name = "bytebot_agent_rs"
path = "src/lib.rs"

[[bin]]
name = "bytebot-agent-rs"
path = "src/main.rs"

[dependencies]
# Web framework and async runtime
axum = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

# Database
sqlx = { workspace = true }
sea-orm = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# HTTP client for AI APIs
reqwest = { workspace = true }

# WebSocket support
tokio-tungstenite = { workspace = true }
socketioxide = { workspace = true }

# Authentication
jsonwebtoken = { workspace = true }
argon2 = { workspace = true }

# Utilities
uuid = { workspace = true }
chrono = { workspace = true }
base64 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
validator = { workspace = true }

# Shared types
bytebot-shared-rs = { path = "../bytebot-shared-rs" }

# Metrics and observability
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
metrics-util = { workspace = true }

# Configuration
envy = "0.4"
dotenvy = "0.15"

# System information
num_cpus = "1.16"

[dev-dependencies]
mockall = { workspace = true }
tokio-test = { workspace = true }
criterion = { workspace = true }
futures = "0.3"
fastrand = "2.0"

[[bench]]
name = "task_benchmarks"
harness = false

[[bench]]
name = "load_test"
harness = false

[[bench]]
name = "memory_profiling"
harness = false